"use server";

import { revalidatePath } from "next/cache";
import { prisma } from "../../../services/database/prisma";
import { rssProcessingQueue, QUEUE_JOB_NAMES } from "../../../jobs/rss/queues/rss.queues";
import { rssFetcherService } from "../../../jobs/rss/services/rss-fetcher.service";
import { requireAdmin } from "../lib/rbac";
import { writeAuditLog } from "../lib/audit";
import { brandSchema, categorySchema, countrySchema, formDataToObject, newsUpdateSchema, sourceSchema } from "../schemas/admin.schemas";

async function actor() { return requireAdmin(); }
async function audit(action: string, entityType: string, entityId?: string, after?: unknown) { const admin = await actor(); await writeAuditLog({ action, entityType, entityId, actorId: admin.id, after }); }

export async function approveNews(id: string) { await actor(); const updated = await prisma.news.update({ where: { id }, data: { status: "PUBLISHED", aiReviewStatus: "approved" } }); await audit("approveNews", "News", id, updated); revalidatePath("/admin/news"); }
export async function rejectNews(id: string) { await actor(); const updated = await prisma.news.update({ where: { id }, data: { status: "REJECTED", aiReviewStatus: "rejected" } }); await audit("rejectNews", "News", id, updated); revalidatePath("/admin/news"); }
export async function archiveNews(id: string) { await actor(); const updated = await prisma.news.update({ where: { id }, data: { status: "ARCHIVED" } }); await audit("archiveNews", "News", id, updated); revalidatePath("/admin/news"); }
export async function updateNews(formData: FormData) { await actor(); const input = newsUpdateSchema.parse(formDataToObject(formData)); const updated = await prisma.news.update({ where: { id: input.id }, data: { title: input.title, excerpt: input.excerpt, body: input.body } }); await audit("updateNews", "News", input.id, updated); revalidatePath(`/admin/news/${input.id}`); }

export async function bulkApproveNews(ids: string[]) { await actor(); await prisma.news.updateMany({ where: { id: { in: ids } }, data: { status: "PUBLISHED", aiReviewStatus: "approved" } }); await audit("bulkApproveNews", "News", undefined, { ids }); revalidatePath("/admin/news"); }
export async function bulkRejectNews(ids: string[]) { await actor(); await prisma.news.updateMany({ where: { id: { in: ids } }, data: { status: "REJECTED", aiReviewStatus: "rejected" } }); await audit("bulkRejectNews", "News", undefined, { ids }); revalidatePath("/admin/news"); }
export async function bulkArchiveNews(ids: string[]) { await actor(); await prisma.news.updateMany({ where: { id: { in: ids } }, data: { status: "ARCHIVED" } }); await audit("bulkArchiveNews", "News", undefined, { ids }); revalidatePath("/admin/news"); }

export async function approveTranslation(id: string) { await actor(); const updated = await prisma.newsTranslation.update({ where: { id }, data: { reviewStatus: "approved" } }); await audit("approveTranslation", "NewsTranslation", id, updated); revalidatePath("/admin/review/translations"); }
export async function rejectTranslation(id: string) { await actor(); const updated = await prisma.newsTranslation.update({ where: { id }, data: { reviewStatus: "rejected" } }); await audit("rejectTranslation", "NewsTranslation", id, updated); revalidatePath("/admin/review/translations"); }
export async function approveProductLaunch(id: string) { await actor(); const updated = await prisma.productLaunch.update({ where: { id }, data: { aiReviewStatus: "approved" } }); await audit("approveProductLaunch", "ProductLaunch", id, updated); revalidatePath("/admin/review/product-launches"); }
export async function rejectProductLaunch(id: string) { await actor(); const updated = await prisma.productLaunch.update({ where: { id }, data: { aiReviewStatus: "rejected" } }); await audit("rejectProductLaunch", "ProductLaunch", id, updated); revalidatePath("/admin/review/product-launches"); }
export async function approveFranchiseOpportunity(id: string) { await actor(); const updated = await prisma.franchiseOpportunity.update({ where: { id }, data: { aiReviewStatus: "approved" } }); await audit("approveFranchiseOpportunity", "FranchiseOpportunity", id, updated); revalidatePath("/admin/review/franchise-opportunities"); }
export async function rejectFranchiseOpportunity(id: string) { await actor(); const updated = await prisma.franchiseOpportunity.update({ where: { id }, data: { aiReviewStatus: "rejected" } }); await audit("rejectFranchiseOpportunity", "FranchiseOpportunity", id, updated); revalidatePath("/admin/review/franchise-opportunities"); }
export async function approveFundingEvent(id: string) { await actor(); const updated = await prisma.fundingEvent.update({ where: { id }, data: { aiReviewStatus: "approved" } }); await audit("approveFundingEvent", "FundingEvent", id, updated); revalidatePath("/admin/review/funding-events"); }
export async function rejectFundingEvent(id: string) { await actor(); const updated = await prisma.fundingEvent.update({ where: { id }, data: { aiReviewStatus: "rejected" } }); await audit("rejectFundingEvent", "FundingEvent", id, updated); revalidatePath("/admin/review/funding-events"); }

export async function createBrand(formData: FormData) { const admin = await actor(); const input = brandSchema.parse(formDataToObject(formData)); const created = await prisma.brand.create({ data: { name: input.name, slug: input.slug, aliases: input.aliases?.split(",").map((x) => x.trim()).filter(Boolean) ?? [], headquartersCountryId: input.countryId || undefined, industryType: input.industryType as any, websiteUrl: input.websiteUrl || undefined, logoUrl: input.logoUrl || undefined, description: input.description } }); await writeAuditLog({ action: "createBrand", entityType: "Brand", entityId: created.id, actorId: admin.id, after: created }); revalidatePath("/admin/brands"); }
export async function updateBrand(id: string, formData: FormData) { const admin = await actor(); const input = brandSchema.parse(formDataToObject(formData)); const updated = await prisma.brand.update({ where: { id }, data: { name: input.name, slug: input.slug, aliases: input.aliases?.split(",").map((x) => x.trim()).filter(Boolean) ?? [], headquartersCountryId: input.countryId || null, industryType: input.industryType as any, websiteUrl: input.websiteUrl || null, logoUrl: input.logoUrl || null, description: input.description } }); await writeAuditLog({ action: "updateBrand", entityType: "Brand", entityId: id, actorId: admin.id, after: updated }); revalidatePath(`/admin/brands/${id}`); }

export async function createCountry(formData: FormData) { const input = countrySchema.parse(formDataToObject(formData)); const created = await prisma.country.create({ data: { name: input.name, slug: input.slug, iso2: input.iso2.toUpperCase(), iso3: input.iso3.toUpperCase(), region: input.region } }); await audit("createCountry", "Country", created.id, created); revalidatePath("/admin/countries"); }
export async function updateCountry(id: string, formData: FormData) { const input = countrySchema.parse(formDataToObject(formData)); const updated = await prisma.country.update({ where: { id }, data: { name: input.name, slug: input.slug, iso2: input.iso2.toUpperCase(), iso3: input.iso3.toUpperCase(), region: input.region } }); await audit("updateCountry", "Country", id, updated); revalidatePath(`/admin/countries/${id}`); }
export async function createCategory(formData: FormData) { const input = categorySchema.parse(formDataToObject(formData)); const created = await prisma.category.create({ data: { name: input.name, slug: input.slug, parentId: input.parentId || undefined, industryType: input.industryType as any, description: input.description } }); await audit("createCategory", "Category", created.id, created); revalidatePath("/admin/categories"); }
export async function updateCategory(id: string, formData: FormData) { const input = categorySchema.parse(formDataToObject(formData)); const updated = await prisma.category.update({ where: { id }, data: { name: input.name, slug: input.slug, parentId: input.parentId || null, industryType: input.industryType as any, description: input.description } }); await audit("updateCategory", "Category", id, updated); revalidatePath(`/admin/categories/${id}`); }
export async function createSource(formData: FormData) { const input = sourceSchema.parse(formDataToObject(formData)); const created = await prisma.source.create({ data: { name: input.name, slug: input.slug, url: input.url, feedUrl: input.url, countryId: input.countryId || undefined, language: input.language.toUpperCase() as any, categoryId: input.categoryId || undefined, active: input.active, isActive: input.active, priority: input.priority, trustScore: input.reliabilityScore, reliabilityScore: input.reliabilityScore, crawlInterval: input.crawlInterval, notes: input.notes || undefined } }); await audit("createSource", "Source", created.id, created); revalidatePath("/admin/sources"); }
export async function updateSource(id: string, formData: FormData) { const input = sourceSchema.parse(formDataToObject(formData)); const updated = await prisma.source.update({ where: { id }, data: { name: input.name, slug: input.slug, url: input.url, feedUrl: input.url, countryId: input.countryId || null, language: input.language.toUpperCase() as any, categoryId: input.categoryId || null, active: input.active, isActive: input.active, priority: input.priority, trustScore: input.reliabilityScore, reliabilityScore: input.reliabilityScore, crawlInterval: input.crawlInterval, notes: input.notes || null } }); await audit("updateSource", "Source", id, updated); revalidatePath(`/admin/sources/${id}`); }
export async function testSourceFetch(id: string) { await actor(); const source = await prisma.source.findUniqueOrThrow({ where: { id } }); await rssFetcherService.fetchFeed({ source: { id: source.id, name: source.name, url: source.url ?? source.feedUrl!, countryId: source.countryId, language: source.language, categoryId: source.categoryId, industryType: source.industryType, active: source.active, lastFetchedAt: source.lastFetchedAt } }); await audit("testSourceFetch", "Source", id); revalidatePath(`/admin/sources/${id}`); }
export async function runSourceFetchNow(id: string) { await actor(); await rssProcessingQueue.add(QUEUE_JOB_NAMES.processSource, { sourceId: id, force: true }, { jobId: `admin-source-fetch:${id}:${Date.now()}` }); await audit("runSourceFetchNow", "Source", id); revalidatePath(`/admin/sources/${id}`); }
