import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Card, CardContent } from "../../../../components/ui/card";
import { NewsCard } from "../../../../features/public/components/news-card";
import { Section } from "../../../../features/public/components/section";
import { getCountryBySlug } from "../../../../features/public/data/intelligence";
import { createPageMetadata } from "../../../../features/public/lib/seo";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const data = await getCountryBySlug(slug); return createPageMetadata({ title: data?.country.name ?? "Country", description: `Food and beverage intelligence for ${data?.country.name ?? slug}.`, path: `/countries/${slug}`, noIndex: !data }); }
export default async function CountryDetailPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const data = await getCountryBySlug(slug); if (!data) notFound(); return <div><h1 className="text-4xl font-black">{data.country.name}</h1><p className="mt-2 text-slate-500">{data.country.region} {data.country.subregion ? `• ${data.country.subregion}` : ""}</p><Section title="Local News"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{data.localNews.map((news) => <NewsCard key={news.id} news={news} />)}</div></Section><Section title="Active Brands"><div className="grid gap-4 md:grid-cols-3">{data.activeBrands.map((brand: any) => <Card key={brand.id}><CardContent><h3 className="font-bold">{brand.name}</h3><p className="text-sm text-slate-500">{brand.industryType}</p></CardContent></Card>)}</div></Section><Section title="Expansion Activities"><div className="grid gap-4 md:grid-cols-2">{data.expansions.map((item: any) => <Card key={item.id}><CardContent><h3 className="font-bold">{item.title}</h3><p className="text-sm text-slate-500">{item.expansionType}</p></CardContent></Card>)}</div></Section><Section title="Market Trends"><div className="grid gap-4 md:grid-cols-2">{data.trends.map((trend: any) => <Card key={trend.id}><CardContent><h3 className="font-bold">{trend.name}</h3><p className="text-sm text-slate-500">{trend.description ?? "Trend signal detected"}</p></CardContent></Card>)}</div></Section><Section title="Franchise Opportunities"><div className="grid gap-4 md:grid-cols-2">{data.franchiseOpportunities.map((item: any) => <Card key={item.id}><CardContent><h3 className="font-bold">{item.title}</h3><p className="text-sm text-slate-500">{item.description}</p></CardContent></Card>)}</div></Section></div>; }
