import { ButtonLink } from "../../components/ui/button";
import { JsonLd } from "../../components/seo/json-ld";
import { Card, CardContent } from "../../components/ui/card";
import { EntityCard } from "../../features/public/components/entity-card";
import { NewsCard } from "../../features/public/components/news-card";
import { ReportCard } from "../../features/public/components/report-card";
import { SearchBar } from "../../features/public/components/search-bar";
import { Section } from "../../features/public/components/section";
import { getHomepageData } from "../../features/public/data/intelligence";
import { createPageMetadata, organizationJsonLd, websiteJsonLd } from "../../features/public/lib/seo";

export const metadata = createPageMetadata({ title: "Real-time Food & Beverage Intelligence", description: "NewsNow-style live intelligence across tea, bubble tea, coffee, restaurant chains, QSR, and FMCG." });

export default async function HomePage() {
  const data = await getHomepageData();
  return <div><JsonLd data={organizationJsonLd()} /><JsonLd data={websiteJsonLd()} /><section className="rounded-3xl bg-gradient-to-br from-slate-950 via-emerald-950 to-slate-900 p-8 text-white md:p-12"><p className="text-sm font-semibold uppercase tracking-[0.3em] text-emerald-300">Live multilingual intelligence</p><h1 className="mt-4 max-w-4xl text-4xl font-black tracking-tight md:text-6xl">Global Food & Beverage Intelligence</h1><p className="mt-5 max-w-2xl text-lg text-slate-300">Track market-moving news, brands, countries, funding, franchise expansion, product launches, and trends in real time.</p><div className="mt-8"><SearchBar /></div></section><Section title="Today’s Intelligence Summary" description="AI-enriched market signals from the latest ingestion cycle."><div className="grid gap-4 md:grid-cols-3"><Card><CardContent><p className="text-3xl font-black">{data.latestNews.length}</p><p className="text-sm text-slate-500">latest articles monitored</p></CardContent></Card><Card><CardContent><p className="text-3xl font-black">{data.trendingBrands.length}</p><p className="text-sm text-slate-500">brands trending today</p></CardContent></Card><Card><CardContent><p className="text-3xl font-black">{data.trendingCountries.length}</p><p className="text-sm text-slate-500">countries with active signals</p></CardContent></Card></div></Section><Section title="Latest News Feed" action={<ButtonLink variant="secondary" href="/news">View all news</ButtonLink>}><div className="grid gap-4 lg:grid-cols-3">{data.latestNews.map((news, index) => <NewsCard key={news.id} news={news} priority={index < 3} />)}</div></Section><Section title="Trending Brands"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">{data.trendingBrands.map((brand) => <EntityCard key={brand.id} href={`/brands/${brand.slug}`} title={brand.name} description={brand.description} stat={`${brand.mentionedCount} mentions`} badge={brand.industryType} />)}</div></Section><Section title="Trending Countries"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">{data.trendingCountries.map((country) => <EntityCard key={country.id} href={`/countries/${country.slug}`} title={country.name} description={country.region} stat={`${country.mentionedCount} mentions`} />)}</div></Section><Section title="Trending Categories"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">{data.trendingCategories.map((category) => <EntityCard key={category.id} href={`/categories/${category.slug}`} title={category.name} stat={`${category.newsCount} articles`} badge={category.industryType} />)}</div></Section><Section title="Featured Reports" action={<ButtonLink variant="secondary" href="/reports">View reports</ButtonLink>}><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{data.reports.map((report) => <ReportCard key={`${report.reportType}-${report.id}`} report={report} />)}</div></Section></div>;
}
