import { notFound } from "next/navigation";
import { AdminPanel } from "../../../../../features/admin/components/admin-cards";
import { AdminForm, Field, TextAreaField } from "../../../../../features/admin/components/admin-forms";
import { ConfirmButton } from "../../../../../features/admin/components/admin-actions";
import { approveNews, rejectNews, updateNews } from "../../../../../features/admin/actions/admin.actions";
import { getAdminNewsDetail } from "../../../../../features/admin/data/admin-loaders";

export default async function AdminNewsDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const news = await getAdminNewsDetail(id); if (!news) notFound();
  return <div className="grid gap-5"><h1 className="text-3xl font-black">Review Article</h1><div className="flex gap-2"><ConfirmButton action={async () => { "use server"; await approveNews(id); }} className="bg-emerald-100 text-emerald-800">Approve</ConfirmButton><ConfirmButton action={async () => { "use server"; await rejectNews(id); }} className="bg-red-100 text-red-800">Reject</ConfirmButton></div><AdminForm action={updateNews}><input type="hidden" name="id" value={news.id} /><Field label="Title" name="title" defaultValue={news.title} required /><TextAreaField label="Excerpt / AI summary" name="excerpt" defaultValue={news.excerpt ?? news.aiSummary} /><TextAreaField label="Body" name="body" defaultValue={news.body} /></AdminForm><AdminPanel title="Translations & Takeaways"><div className="grid gap-4 md:grid-cols-2">{news.translations.map((t) => <div key={t.id} className="rounded-xl border p-4"><b>{t.language}: {t.title}</b><p className="mt-2 text-sm text-slate-500">{t.aiSummary}</p><ul className="mt-2 list-disc pl-5 text-sm">{t.keyTakeaways.map((x) => <li key={x}>{x}</li>)}</ul></div>)}</div></AdminPanel><AdminPanel title="Detected Entities"><div className="grid gap-4 md:grid-cols-3"><div><h3 className="font-bold">Brands</h3>{news.brandMentions.map((m) => <p key={m.id}>{m.brand.name} ({m.confidence})</p>)}</div><div><h3 className="font-bold">Countries</h3>{news.countryMentions.map((m) => <p key={m.id}>{m.country.name} ({m.confidence})</p>)}</div><div><h3 className="font-bold">Tags</h3>{news.tags.map((m) => <p key={m.tagId}>{m.tag.name}</p>)}</div></div><p className="mt-4 text-sm text-slate-500">Source URL: {news.canonicalUrl ?? news.originalUrl}</p></AdminPanel></div>;
}
